### ISSUE TITLE
Update to Symfony 5

### ISSUE THREAD

**Issue by bobdenotter** [bolt/core#1182]
Currently, Bolt 4 uses SF 4 components. We should bump these to v5. 

- [x] Replace Behat / MinkBrowserKitDriver with updated forks -> See #1474
- [x] Replace PagerFanta with `BabDev/BabDevPagerfantaBundle`
- [x] Remove `doctrine/doctrine-cache-bundle`
- [x] Fix deprecations in SF 4.4
- [x] use `error_controller` under "framework", instead of `exception_controller` under "twig" -> See #1477

**Comment by bobdenotter** [comment]
Behat / MinkBrowserKitDriver needs to be updated, but it seems work is underway: 

https://github.com/minkphp/MinkBrowserKitDriver/pull/142

**Comment by bobdenotter** [comment]
Same for PagerFanta: 

- https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/issues/224
- Fork here: https://github.com/BabDev/BabDevPagerfantaBundle

**Comment by bobdenotter** [comment]
Other findings: 

We need to fix deprecations: 

```
!!
!!  Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\DependencyInjection\ContainerBuilder::set() must be an object or null, array given, called in /foo/src/Kernel.php on line 95 and defined in /foo/vendor/symfony/dependency-injection/ContainerBuilder.php:484
!!  Stack trace:
!!  #0 /foo/src/Kernel.php(95): Symfony\Component\DependencyInjection\ContainerBuilder->set('bolt.config.gen...', Array)
!!  #1 /foo/src/Kernel.php(64): Bolt\Kernel->setBoltParameters(Object(Symfony\Component\DependencyInjection\ContainerBuilder), '/Users/bob/Site...')
!!  #2 /foo/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(118): Bolt\Kernel->configureContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Symfony\Component\Config\Loader\DelegatingLoader))
!!  #3 /foo/vendor/symfony/dependency-injection/Loader/ClosureLoader.php(38): Bolt\Kernel->Symfony\Bundle\FrameworkBundle\Kernel in /foo/vendor/symfony/dependency-injection/ContainerBuilder.php on line 484
!!  PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\DependencyInjection\ContainerBuilder::set() must be an object or null, array given, called in /foo/src/Kernel.php on line 95 and defined in /foo/vendor/symfony/dependency-injection/ContainerBuilder.php:484
!!  Stack trace:
!!  #0 /foo/src/Kernel.php(95): Symfony\Component\DependencyInjection\ContainerBuilder->set('bolt.config.gen...', Array)
!!  #1 /foo/src/Kernel.php(64): Bolt\Kernel->setBoltParameters(Object(Symfony\Component\DependencyInjection\ContainerBuilder), '/Users/bob/Site...')
!!  #2 /foo/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(118): Bolt\Kernel->configureContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Symfony\Component\Config\Loader\DelegatingLoader))
!!  #3 /foo/vendor/symfony/dependency-injection/Loader/ClosureLoader.php(38): Bolt\Kernel->Symfony\Bundle\FrameworkBundle\Kernel in /foo/vendor/symfony/dependency-injection/ContainerBuilder.php on line 484
```

And remove `doctrine/doctrine-cache-bundle`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/security-bundle ^5.1 -> satisfiable by symfony/security-bundle[v5.1.0, v5.1.1].
    - doctrine/doctrine-cache-bundle 1.4.0 requires symfony/doctrine-bridge ^3.4|^4.0 -> satisfiable by symfony/doctrine-bridge[v4.4.10].
    - doctrine/doctrine-cache-bundle 1.4.0 requires symfony/doctrine-bridge ^3.4|^4.0 -> satisfiable by symfony/doctrine-bridge[v4.4.10].
    - Conclusion: remove symfony/doctrine-bridge v4.4.10
    - Installation request for doctrine/doctrine-cache-bundle ^1.4 -> satisfiable by doctrine/doctrine-cache-bundle[1.4.0].
```

**Comment by bobdenotter** [comment]
New one: 

```
Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Debug' not found in /Users/bob/Sites/bolt/core/public/index.php:26 Stack trace: #0 {main} thrown in /Users/bob/Sites/bolt/core/public/index.php on line 26
```

**Comment by bobdenotter** [comment]
Making progress.. Seems the only blocker is now Behat: 

![Screenshot 2020-06-15 at 11 00 07](https://user-images.githubusercontent.com/1833361/84638624-86350c00-aef7-11ea-86c4-517e1214ec92.png)
