### ISSUE TITLE
Error in ``bin/console extensions:configure --with-config` when running create-project

### ISSUE THREAD

**Issue by mcdennem** [bolt/core#1651]
Creating a new project with composer break

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | Bolt RC32
| Install type                   | Composer install
| BC Break                     | ???
| PHP version                 | 7.3 |
| Web server                  | Apache
| For UX/UI issues        | N/A

Reproduction
------------

Run `composer create-project bolt/project myproject`

### Expected result

Bolt project should be created without any errors in the terminal.

### Actual result

```
Fatal error: Uncaught Error: Class 'ComposerPackages\Types' not found in C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\bolt\core\src\Extension\Extens
ionCompilerPass.php:83
Stack trace:
#0 C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\bolt\core\src\Extension\ExtensionCompilerPass.php(48): Bolt\Extension\ExtensionCompilerPass->addComp
oserPackages(Array)
#1 C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\bolt\core\src\Extension\ExtensionCompilerPass.php(34): Bolt\Extension\ExtensionCompilerPass->buildSe
rvices(Array)
#2 C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\symfony\dependency-injection\Compiler\Compiler.php(91): Bolt\Extension\ExtensionCompilerPass->proces
s(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\symfony\dependency-injection\ContainerBuilder.php(736): Symfony\Component\DependencyInjection\Compil
er\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 C:\wamp64\www\core-4.0.0-rc.32\myproje in C:\wamp64\www\core-4.0.0-rc.32\myprojectname\vendor\bolt\core\src\Extension\ExtensionCompilerPass.php on line
83
Script php bin/console extensions:configure --with-config handling the post-install-cmd event returned with error code 255
```

**Comment by bobdenotter** [comment]
Is this still an issue? I believe it worked correctly for you yesterday, right?

**Comment by mcdennem** [comment]
That's correct, this issue is resolved.

**Comment by bobdenotter** [comment]
Let's close it then!
